package org.possystem.entity;

import java.time.LocalDateTime;

/**
 * Record class for TransactionDiscount entity.
 * Represents discounts applied to transactions (Senior, Veteran, Promotional, Coupon).
 *
 * Auto-generated by Java Record:
 * - All-args constructor
 * - Getters (id(), transactionId(), discountType(), discountAmount(),
 *            itemId(), status(), createdAt())
 * - toString()
 * - equals()
 * - hashCode()
 * Note: Records are immutable, no setters generated.
 */
public record TransactionDiscount(
        int id,
        int transactionId,
        String discountType,      // 'SENIOR', 'VETERAN', 'PROMOTIONAL', 'COUPON'
        double discountAmount,    // Negative value (e.g., -5.00)
        Integer itemId,           // NULL for cart-level discounts, FK to transaction_items for item-level
        String status,            // 'ACTIVE' or 'REMOVED'
        LocalDateTime createdAt
) {}
