package org.possystem.entity;

import java.time.LocalDateTime;

/**
 * Record class for TransactionPayment entity.
 * Represents individual payments made toward a transaction (for split payment support).
 *
 * Auto-generated by Java Record:
 * - All-args constructor
 * - Getters (id(), transactionId(), paymentType(), amount(),
 *            paymentOrder(), createdAt())
 * - toString()
 * - equals()
 * - hashCode()
 * Note: Records are immutable, no setters generated.
 */
public record TransactionPayment(
        int id,
        int transactionId,
        String paymentType,       // 'CASH' or 'CARD'
        double amount,            // Payment amount (positive value)
        int paymentOrder,         // 1st, 2nd, 3rd payment, etc.
        LocalDateTime createdAt
) {}
